name: Greetings

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    name: Greet first-time contributors
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/first-interaction@v3
        with:
          issue_message: "This is your first time submitting an issue with NetSonar 🥳Please review your issue and ensure that the submit template was followed, the information is complete, and not related to any other open issue. It will be reviewed shortly. Debugging is very important and make the program better. Thanks for contributing and making the software better! 🙌"
          pr_message: "This is your first time submitting a pull request with NetSonar 🥳Please review your PR and ensure that the submit template was followed, the information is complete, and not related to any other open PR. PRs by community are very important and make the software better and richer in every way. Thanks for contributing and making the software better! 🙌"
